# Generated by Django 5.2.6 on 2025-12-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectimage_projectvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='whatsapp_number',
            field=models.CharField(default='+919833010277', help_text='Number for inquiry (without spaces)', max_length=20),
        ),
    ]
